services:
  # ── Application ─────────────────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 1808561084/sms:v1
    container_name: bionic_app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      CI_ENVIRONMENT: ${CI_ENVIRONMENT}
      APP_BASE_URL: ${APP_BASE_URL}
      COOKIE_DOMAIN: ""
      DB_HOST: ${DB_HOST:?DB_HOST cannot empty}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DRIVER: Postgre
      DB_PORT: 5432
      CACHE_HANDLER: redis
      CACHE_BACKUP_HANDLER: file
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      AUTO_SEED: true
      SEED_FORCE: false
      SEEDER_CLASS: MainSeeder
    volumes:
      - app_writable:/var/www/html/writable
      - public_uploads:/var/www/html/public/uploads/revisions
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bionic_net

  # ── Database ─────────────────────────────────────────────────────────────────
  db:
    image: postgres:18.3
    container_name: bionic_db
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - PGDATA=/var/lib/postgresql/18/docker
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bionic_user -d bionic_db" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - bionic_net

  # ── Cache ───────────────────────────────────────────────────────────────────
  redis:
    image: redis:alpine
    container_name: bionic_redis
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    expose:
      - 6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - bionic_net

volumes:
  db_data:
    name: "my-app-data"
  app_writable:
  redis_data:
  public_uploads:

networks:
  bionic_net:
    driver: bridge
