services:
  # ── Application ─────────────────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 1808561084/sms:v1
    container_name: bionic_app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      CI_ENVIRONMENT: production
      APP_BASE_URL: http://localhost:8080/
      COOKIE_DOMAIN: ""
      DB_HOST: db
      DB_NAME: bionic_db
      DB_USER: bionic_user
      DB_PASS: Bionic@natura123
      DB_DRIVER: Postgre
      DB_PORT: 5432
      CACHE_HANDLER: redis
      CACHE_BACKUP_HANDLER: file
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      # from here are custom env vars for the app
      AUTO_SEED: true
      SEED_FORCE: false
      SEEDER_CLASS: MainSeeder
    volumes:
      - app_writable:/var/www/html/writable
      - public_uploads:/var/www/html/public/uploads/revisions
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bionic_net

  # ── Database ─────────────────────────────────────────────────────────────────
  db:
    image: postgres:18.3
    container_name: bionic_db
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/18/docker
      - POSTGRES_DB=bionic_db
      - POSTGRES_USER=bionic_user
      - POSTGRES_PASSWORD=Bionic@natura123
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bionic_user -d bionic_db" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - bionic_net

  # ── Cache ───────────────────────────────────────────────────────────────────
  redis:
    image: redis:alpine
    container_name: bionic_redis
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - bionic_net

volumes:
  db_data:
    name: "my-app-data"
  app_writable:
  redis_data:
  public_uploads:

networks:
  bionic_net:
    driver: bridge
